### PR TITLE
Use your own repo?

### PR DESCRIPTION
**Pull request by ctjhoa**
Your project is very interesting and it's definitely an enhancement in front of the old `vim-alias`. I'm using it for [ctjhoa/spacevim](https://github.com/ctjhoa/spacevim/tree/dev) and I'm very happy with alias for non-word chars.

As your project is a fork, nobody can open issue (to report bugs or add suggestion) so could you create your own repo to host this project?

PS: this PR is nonsense, I didn't find a better way to contact you.

### CODE REVIEW

**Comment by Konfekt** [comment]
I think foremost the current URL, Konfekt/vim-alias, has to be kept. The only solution that comes to my mind, for creating my own repo and keeping the URL, is deleting this repo, and uploading it again. But that would destroy its history. I will do so once I'm sure there's no other way.

**Comment by ctjhoa** [comment]
I think you can keep your git history with something like https://help.github.com/articles/duplicating-a-repository/

**Comment by ctjhoa** [comment]
Or you can ask gthub support to detach fork and turn it into a standalone repo as explained in https://help.github.com/articles/why-are-my-contributions-not-showing-up-on-my-profile/#commit-was-made-in-a-fork

With this method you will keep stargazers also

**Comment by Konfekt** [comment]
Ok. I sent a request to Github.

**Comment by Konfekt** [comment]
Request accepted.

**Comment by ctjhoa** [comment]
@Konfekt nice thanks!

**Pull request closed without merging**
